### PR TITLE
Gbdev14 issue 29

### LINKED ISSUE #29: #gbdev compo 2014
[gbdev2014-allroms.zip](https://github.com/gbdev/database/files/2202719/gbdev2014-allroms.zip)

### PR DESCRIPTION
**Pull request by dag7dev**
Close #29 

Everything's ready for merging!

### CODE REVIEW

**Comment by avivace** [comment]
I'm not sure why this PR changes the slugs for every entry?

**Comment by dag7dev** [comment]
> I'm not sure why this PR changes the slugs for every entry?

Because I created it from gambit-importer branch, and when I created gambit-importer branch I created RUN_THIS blah that renames every folder, fixes game.json slug file and order every json file key.

In fact, even in gambit-importer branch you will find the same behaviour.

**Comment by avivace** [comment]
> > I'm not sure why this PR changes the slugs for every entry?
> 
> Because I created it from gambit-importer branch, and when I created gambit-importer branch I created RUN_THIS blah that renames every folder, fixes game.json slug file and order json keys for each game.json file .
> 
> In fact, even in gambit-importer branch you will find the same behaviour.
> 
> Make sure to merge first gambit, then this, because I did an additional commit there which it is not here.
> 
> (additionally, I need to figure out how to add it in gbdev14-issue-29 without creating a mess)

Sorry, but this makes no sense. Every PR /especially scrapers must be branched from `main`. Basing a PR on the history of another one makes the work blocked (and blocking), un-testable and un-mergeable, especially in these cases when the "source" PR is completely out of context.

Please, re-base the PR from `main` and don't introduce anything BUT the actual new scraper (and not the entries)

**Review by avivace — CHANGES_REQUESTED** [review]
Please, create a PR including only the new scraper, branched off from master

**Pull request closed without merging**
