### PR TITLE
Entry Proposal "Bannerprint"

### PR DESCRIPTION
**Pull request by reini1305**
This PR adds my first homebrew ROM to the list: a ROM that can be used with the Gameboy Printer to print text banners.

### CODE REVIEW

**Comment by avivace** [comment]
Hey @reini1305 this looks super cool! The PR doesn't validate against the schema because we don't have a "gbprinter" tag yet. I'll add it and ping you back

**Comment by reini1305** [comment]
Soory, I've overread that one can only select from the tags that are present. I'm happy to remove it, but having it as a possible tag would be awesome too :)

**Comment by avivace** [comment]
> Sorry, I've didn't realize that one can only select from the tags that are present. I'm happy to remove it, but having it as a possible tag would be awesome too :)

Okay, I just added `gbprinter` as possible tag in the schema. It should be enough to replace the `Printer` tag you with `gbprinter` to let it pass

**Comment by reini1305** [comment]
Thanks! I've updated the tags.

**Review by avivace — APPROVED** [review]

**Comment by avivace** [comment]
Should be safe to merge. The CI will fail anyway here because Github CI ignores updates to the base branch CI pipeline

**Pull request merged**
