### PR TITLE
entries: Remove duplicates

### PR DESCRIPTION
**Pull request by asiekierka**
Will solve https://github.com/gbdev/database/issues/134

### CODE REVIEW

**Review by avivace — APPROVED** [review]

**Comment by dag7dev** [comment]
@asiekierka @avivace how has the cleanup been executed? Using a particular cleanup script? I remember having done a similar work, but at the time it was discarded. https://github.com/gbdev/database/pull/157
(for the sake of curiosity and clarity, nothing more!)

**Comment by asiekierka** [comment]
I edited every single duplicate entry hand.

**Comment by dag7dev** [comment]
@asiekierka I agree with you! I did the same thing at the time, and I remember a comment (https://github.com/gbdev/database/pull/157#issuecomment-1114808679) where "at most 30 items were allowed".

Is this policy changed then?

**Comment by asiekierka** [comment]
I wasn't aware of that policy :-) However:

(a) I split it into multiple commits, so they could be PR'd and reviewed separately if need be.
(b) I didn't do any other changes, which is why my PR has 635 diffs and not 2000+. Much smaller, thus easier to review.

**Review by avivace — APPROVED** [review]

**Pull request merged**
