### PR TITLE
Adding new game to the database "Crystal Lake" by VHVS.

### PR DESCRIPTION
**Pull request by v666**
Adding new game to the database "Crystal Lake" by VHVS.

### CODE REVIEW

**Comment by v666** [comment]
Sorry, bad json...will submit again.

**Comment by avivace** [comment]
Oh hey @v666 thanks for the contribution. Just an heads up for the next time: you can "force-push" to the same branch if anything goes wrong so you don't have to open another PR

**Comment by v666** [comment]
So I can do a force-push so the change checks in, because the pull request is still associated to my fork/branch right...?
Oh, I'm quite a noob in github :P. Thanks for the advice.

**Comment by avivace** [comment]
> So I can do a force-push so the change checks in, because the pull request is still associated to my fork/branch right...?
> Oh, I'm quite a noob in github :P. Thanks for the advice.

Yes, exactly. It was a general suggestion though, the new PR was perfectly fine :D

**Pull request closed without merging**
