### PR TITLE
Adding new game entry - Crystal Lake by VHVS.

### PR DESCRIPTION
**Pull request by v666**
Adding new game entry - Crystal Lake by VHVS.

### CODE REVIEW

**Review by avivace — APPROVED** [review]

**Comment by avivace** [comment]
Looks good to me! Thank you @v666

**Comment by v666** [comment]
Thank you.
BTW, I think adding the User's manual would be nice.
Should I place this PDF file in the Crystal-Lake folder along with the rom and the screenshots?
Thanks!

**Comment by avivace** [comment]
Yes! You can add another entry to the `files` array (just be sure to not mark it as playable). The frontend is not currently rendering or serving any of the non-ROM files, but we can work on that :P

**Comment by v666** [comment]
Thanks Antonio.
Oh yes -I do forgot about the game.json in the folder, of course.
I had previously sent another pull request with the PDF file - I guess you can cancel that one?
Thanks!

**Comment by avivace** [comment]
@v666 Yes, feel free to open a new one adding the PDF, we just closed (without merging) the old one, so it's ignored now :)

**Comment by v666** [comment]
@avivace Thanks for following this up.
You're being super helpful.
Question - I have my fork - and I have everything in my HDD.
What is it I must do in order to update my fork (v666:master) with gbdev:master?
Or am I still able to use my fork as it is?
I haven't done anything else but what I added in my last pull request.
Thanks.

**Comment by avivace** [comment]
Yes, you can keep your fork/local repository, just sync it back to upstream (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) and then re-branch from it.
Once you've committed to your new branch, just push it again and you should be able to send a new PR from the GitHub UI

**Pull request merged**
