### PR TITLE
Adding some additional files related to Crystal Lake.

### PR DESCRIPTION
**Pull request by v666**
Adding some additional files related to Crystal Lake.
Instructions Manual and readme.

### CODE REVIEW

**Comment by v666** [comment]
@avivace 
Thanks for all your help - I think I got it :)

**Comment by avivace** [comment]
> I think I got it :)
Yes, you did! I've opened https://github.com/gbdev/homebrewhub/issues/60 and https://github.com/gbdev/homebrewhub/issues/60 to track the work on actually showing those values (website, the other files) on the frontend

**Comment by v666** [comment]
@avivace Thanks a lot - I feel I had a 1 day github crash course XD,
Let me know if I can do anything.

**Comment by avivace** [comment]
> @avivace Thanks a lot - I feel I had a 1 day github crash course XD,
> Let me know if I can do anything.

That's great to hear! Now you can use GitHub to build great things :rocket: :grin: 

The game is now online at https://gbhh.avivace.com/game/Crystal-Lake but some of the additional properties are not gonna be shown until we update the views on the frontend (see the issues I mentioned in my previous message).

**Comment by v666** [comment]
@avivace Thanks Antonio.
Yes, github is interesting.
I'm glad the game in online! I'm proud of it.
It's built with GB Studio, but, hell, it's a good game.

Is there anything I can do to help you on the frontend requirements?
Thanks again.

**Comment by v666** [comment]
@avivace I see the game online, but it does not appear when I browse.
Is that expected? Thanks!

**Pull request merged**
