### PR TITLE
added JP - homebrew game by Graham Coulby

### PR DESCRIPTION
**Pull request by gcoulby**
I have added a recent homebrew development for consideration.

### CODE REVIEW

**Comment by avivace** [comment]
Oh hi @gcoulby ! PR looks okay, thank you!

The only screenshot I see pictures the "Press Start" screen, maybe you could another one with the actual gameplay? I think it could help :P

**Review by avivace — CHANGES_REQUESTED** [review]
Another screenshot would be great !

**Comment by gcoulby** [comment]
First time I've seen this if I am honest. The instructions say: "Add more commits by pushing to the master branch on gcoulby/database.", so this is what I have done. I have added screenshots of the splash screen, welcome screen, game play and death state. 

Should you need anything further please let me know.

**Comment by avivace** [comment]
Looks great now to me! Thanks @gcoulby

**Comment by gcoulby** [comment]
How often is the website updated to reflect newly added content?

**Pull request merged**
